### ISSUE TITLE
Add debit card

### ISSUE THREAD

**Issue by ISL270** [DroidsOnRoids/add-to-google-wallet#11]
Can this package be used to add debit card from my app to google wallet?

**Comment by ryanhz** [comment]
@ISL270 No, you can add to Google Wallet,  only Wallet passes.  Only approved pass provider can issue passes.

**Comment by michalowskim** [comment]
@ISL270 Unfortunately you can't use this package to add debit card. This feature is only available to card issuers and requires additional access.
